version: '3'

services:
  vueapp:
    build:
      context: ./infra/dev/node
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
